
version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/node:14.15"
      # - image: "cimg/base:stable"
    steps:
      # install node and checkout code
      - node/install:
          node-version: '14.15'         
    #   - checkout
      - eb/setup
      - aws-cli/setup
      - checkout
      # Use root level package.json to install dependencies in the frontend app
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      # TODO: Install dependencies in the the backend API          
      - run:
          name: Install API Dependencies
          command: |
            npm run backend:install
      # TODO: Build the frontend app
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      # TODO: Build the backend API      
      - run:
          name: API Build
          command: |
            npm run backend:build
      - run:
          name: Deploy Frontend Application
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy Backend Application
          command: |
            npm run backend:deploy
#   # deploy step will run only after manual approval
# #   deploy:
#     docker:
#       - image: "cimg/base:stable"
#       # more setup needed for aws, node, elastic beanstalk
#     steps:

            
workflows:
  udagram:
    jobs:
      - build :
          filters:
            branches:
              only:
                - main
    #       type: approval
    #       requires:
    #         - build
    #   - deploy